version: "3.8"

networks:
  traefik-proxy-blumilk-local:
    external: true

services:
  whoami:
    image: traefik/whoami
    container_name: traefik-whoami-container
    labels:
      - "traefik.enable=true"
      - "traefik.blumilk.environment=true"
      # HTTP
      - "traefik.http.routers.whoami-http-router.rule=Host(`whoami.blumilk.localhost`)"
      - "traefik.http.routers.whoami-http-router.entrypoints=web"
    networks:
      - traefik-proxy-blumilk-local
