version: "3.8"

networks:
  traefik-proxy-vama-local:
    external: true

services:
  whoami:
    image: traefik/whoami
    container_name: traefik-whoami-container
    labels:
      - "traefik.enable=true"
      # HTTP
      - "traefik.http.routers.whoami-http-router.rule=Host(`whoami.vama.localhost`)"
      - "traefik.http.routers.whoami-http-router.entrypoints=web"
    networks:
      - traefik-proxy-vama-local
