networks:
  traefik-proxy-vama-local:
    external: true

services:
  traefik-proxy-vama-local-service:
    image: traefik:v2.9.8
    container_name: traefik-proxy-vama-local-container
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.vama.environment=true"
      # HTTP
      - "traefik.http.routers.traefik-dashboard-http-router.rule=Host(`${TRAEFIK_DASHBOARD_HOST_NAME}`)"
      - "traefik.http.routers.traefik-dashboard-http-router.service=api@internal"
      - "traefik.http.routers.traefik-dashboard-http-router.entrypoints=web"
    networks:
      - traefik-proxy-vama-local
    ports:
      # web entrypoint
      - ${TRAEFIK_WEB_ENTRYPOINT_HOST_PORT}:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # static config file
      - ./config/static/traefik.yaml:/etc/traefik/traefik.yaml
      # dynamic config directory
      - ./config/dynamic:/etc/traefik/config/dynamic