global:
    checkNewVersion: true
    sendAnonymousUsage: false

log:
    level: ERROR

entryPoints:
    web:
        address: ":80"

api:
    insecure: false
    dashboard: true

providers:
    file:
        directory: "/etc/traefik/config/dynamic"
        watch: true
    docker:
        network: "traefik-proxy-vama-local"
        exposedByDefault: false

experimental:
    http3: true
